<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Taskflow — My tasks</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="min-h-screen bg-[#f7f8fc] font-sans text-slate-900 antialiased">
        <div class="min-h-screen lg:grid lg:grid-cols-[250px_1fr]">
            <aside class="flex flex-col bg-[#1f2440] px-5 py-6 text-slate-300 lg:min-h-screen">
                <a href="{{ route('dashboard') }}" class="flex items-center gap-3 text-white"><span class="grid size-9 place-items-center rounded-xl bg-[#756cf1] text-lg font-bold">✓</span><span class="text-xl font-bold tracking-tight">taskflow</span></a>
                <nav class="mt-10 space-y-1" aria-label="Main navigation">
                    <a href="{{ route('dashboard') }}" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition hover:bg-white/8 hover:text-white">▦ Dashboard</a>
                    <a href="{{ route('task') }}" class="flex items-center gap-3 rounded-xl bg-white/10 px-3 py-2.5 text-sm font-semibold text-white">✓ My tasks <span class="ml-auto rounded-md bg-white/10 px-1.5 py-0.5 text-xs">12</span></a>
                    <a href="#projects" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition hover:bg-white/8 hover:text-white">□ Projects</a>
                    <a href="#calendar" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition hover:bg-white/8 hover:text-white">▣ Calendar</a>
                </nav>
                <div class="mt-8 border-t border-white/10 pt-6"><p class="px-3 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Workspace</p><a href="#team" class="mt-3 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium hover:bg-white/8 hover:text-white"><span class="grid size-5 place-items-center rounded-md bg-amber-300 text-[10px] font-bold text-amber-950">A</span>Acme Studio</a></div>
                <div class="mt-auto flex items-center gap-3 border-t border-white/10 pt-5"><div class="grid size-9 place-items-center rounded-full bg-gradient-to-br from-pink-300 to-violet-400 text-sm font-bold text-white">JD</div><div><p class="text-sm font-semibold text-white">Jordan Davis</p><p class="text-xs text-slate-400">Product designer</p></div></div>
            </aside>

            <main class="min-w-0 px-5 py-6 sm:px-8 lg:px-10 lg:py-8">
                <header class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-sm font-medium text-slate-500">Thursday, October 24</p><h1 class="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">My tasks</h1></div><div class="flex gap-2"><button type="button" class="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-medium text-slate-600 shadow-sm">Filter</button><button type="button" class="rounded-xl bg-[#756cf1] px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-200">＋ New task</button></div></header>
                <section class="mt-8 flex flex-wrap gap-3" aria-label="Task summary"><span class="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm">All <span class="ml-2 text-slate-400">12</span></span><span class="rounded-xl bg-indigo-50 px-4 py-2 text-sm font-semibold text-[#756cf1]">In progress <span class="ml-2">5</span></span><span class="rounded-xl bg-rose-50 px-4 py-2 text-sm font-semibold text-rose-600">Overdue <span class="ml-2">3</span></span><span class="rounded-xl bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-600">Completed <span class="ml-2">4</span></span></section>

                <div class="mt-6 space-y-6">
                    <section class="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><header class="flex items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6"><div class="flex items-center gap-3"><span class="grid size-8 place-items-center rounded-lg bg-indigo-50 text-sm font-bold text-[#756cf1]">◷</span><div><h2 class="font-bold">In progress</h2><p class="text-sm text-slate-500">5 active tasks</p></div></div><span class="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-[#756cf1]">5</span></header><div class="divide-y divide-slate-100">
                        <article class="flex gap-3 px-5 py-4 sm:px-6"><button type="button" class="mt-0.5 size-5 shrink-0 rounded-full border-2 border-slate-300" aria-label="Complete Review onboarding flow"></button><div class="min-w-0 grow"><div class="flex flex-wrap justify-between gap-2"><div><h3 class="font-semibold">Review onboarding flow</h3><p class="mt-1 text-sm text-slate-500">Review final copy and handoff notes for the new customer screens.</p></div><button type="button" class="text-slate-400">•••</button></div><div class="mt-3 flex flex-wrap items-center gap-2 text-xs"><span class="rounded-md bg-rose-50 px-2 py-1 font-semibold text-rose-600">High priority</span><span class="rounded-md bg-slate-100 px-2 py-1 font-medium text-slate-600">Website redesign</span><span class="text-rose-500">Due today, 10:00 AM</span></div></div></article>
                        <article class="flex gap-3 px-5 py-4 sm:px-6"><button type="button" class="mt-0.5 size-5 shrink-0 rounded-full border-2 border-slate-300" aria-label="Complete Design system check-in"></button><div class="min-w-0 grow"><div class="flex flex-wrap justify-between gap-2"><div><h3 class="font-semibold">Design system check-in</h3><p class="mt-1 text-sm text-slate-500">Align on new component states with the design team.</p></div><button type="button" class="text-slate-400">•••</button></div><div class="mt-3 flex flex-wrap items-center gap-2 text-xs"><span class="rounded-md bg-amber-50 px-2 py-1 font-semibold text-amber-600">Medium priority</span><span class="rounded-md bg-slate-100 px-2 py-1 font-medium text-slate-600">Brand guidelines</span><span class="text-slate-500">Due today, 1:30 PM</span></div></div></article>
                        <article class="flex gap-3 px-5 py-4 sm:px-6"><button type="button" class="mt-0.5 size-5 shrink-0 rounded-full border-2 border-slate-300" aria-label="Complete Finalize Q4 campaign brief"></button><div class="min-w-0 grow"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold">Finalize Q4 campaign brief</h3><button type="button" class="text-slate-400">•••</button></div><div class="mt-3 flex flex-wrap items-center gap-2 text-xs"><span class="rounded-md bg-emerald-50 px-2 py-1 font-semibold text-emerald-600">Low priority</span><span class="rounded-md bg-slate-100 px-2 py-1 font-medium text-slate-600">Marketing</span><span class="text-slate-500">Due tomorrow</span></div></div></article>
                    </div></section>

                    <section class="overflow-hidden rounded-2xl border border-rose-100 bg-white shadow-sm"><header class="flex items-center justify-between border-b border-rose-100 px-5 py-4 sm:px-6"><div class="flex items-center gap-3"><span class="grid size-8 place-items-center rounded-lg bg-rose-50 text-sm font-bold text-rose-600">!</span><div><h2 class="font-bold">Overdue</h2><p class="text-sm text-rose-500">Needs your attention</p></div></div><span class="rounded-full bg-rose-50 px-2.5 py-1 text-xs font-semibold text-rose-600">3</span></header><div class="divide-y divide-slate-100">
                        <article class="flex gap-3 px-5 py-4 sm:px-6"><button type="button" class="mt-0.5 size-5 shrink-0 rounded-full border-2 border-rose-300" aria-label="Complete Send user interview notes"></button><div class="min-w-0 grow"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold">Send user interview notes</h3><button type="button" class="text-slate-400">•••</button></div><div class="mt-3 flex flex-wrap items-center gap-2 text-xs"><span class="rounded-md bg-rose-50 px-2 py-1 font-semibold text-rose-600">High priority</span><span class="rounded-md bg-slate-100 px-2 py-1 font-medium text-slate-600">Research</span><span class="font-semibold text-rose-600">2 days overdue</span></div></div></article>
                        <article class="flex gap-3 px-5 py-4 sm:px-6"><button type="button" class="mt-0.5 size-5 shrink-0 rounded-full border-2 border-rose-300" aria-label="Complete Update launch checklist"></button><div class="min-w-0 grow"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold">Update launch checklist</h3><button type="button" class="text-slate-400">•••</button></div><div class="mt-3 flex flex-wrap items-center gap-2 text-xs"><span class="rounded-md bg-amber-50 px-2 py-1 font-semibold text-amber-600">Medium priority</span><span class="rounded-md bg-slate-100 px-2 py-1 font-medium text-slate-600">Mobile app launch</span><span class="font-semibold text-rose-600">Yesterday</span></div></div></article>
                    </div></section>

                    <section class="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><header class="flex items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6"><div class="flex items-center gap-3"><span class="grid size-8 place-items-center rounded-lg bg-emerald-50 text-sm font-bold text-emerald-600">✓</span><div><h2 class="font-bold">Completed</h2><p class="text-sm text-slate-500">Finished this week</p></div></div><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-600">4</span></header><div class="divide-y divide-slate-100">
                        <article class="flex gap-3 px-5 py-4 sm:px-6"><button type="button" class="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-emerald-500 text-xs text-white" aria-label="Completed Prepare sprint recap">✓</button><div class="min-w-0 grow"><h3 class="font-medium text-slate-400 line-through">Prepare sprint recap</h3><div class="mt-3 flex flex-wrap items-center gap-2 text-xs"><span class="rounded-md bg-slate-100 px-2 py-1 font-medium text-slate-500">Marketing</span><span class="text-slate-400">Completed today at 9:20 AM</span></div></div></article>
                        <article class="flex gap-3 px-5 py-4 sm:px-6"><button type="button" class="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-emerald-500 text-xs text-white" aria-label="Completed Approve design mockups">✓</button><div class="min-w-0 grow"><h3 class="font-medium text-slate-400 line-through">Approve design mockups</h3><div class="mt-3 flex flex-wrap items-center gap-2 text-xs"><span class="rounded-md bg-slate-100 px-2 py-1 font-medium text-slate-500">Website redesign</span><span class="text-slate-400">Completed yesterday</span></div></div></article>
                    </div></section>
                </div>
            </main>
        </div>
    </body>
</html>
